### ISSUE TITLE
Aesthetical Suggestions

### ISSUE THREAD

**Issue by kilbith** [paramat/biomesdev#1]
I take a bit of advance in my feedbacks since I'll take some holidays shortly.

The biomes are overall a nice work currently, but after a long ride I want to list some oddities that should change IMO...

- **[Pine Tree]** The horizontal trunks are a good idea for shifting the leaves and place decorations between the trunk and the leaves (excellent for the apples for example). But it's too excessively used on the pine tree and cause problems for several reasons : 
    * A forrest is supposed to be "wild and highly vegetal-feeling". With all those horizontal trunks you end up seeing "clear spots" everywhere (ugly) and this doesn't look like a forrest :
![screenshot_20150718_150116](https://cloud.githubusercontent.com/assets/7883281/8761916/45647996-2d69-11e5-86b3-4547ec993e4c.png)

    * Please note : the pine's branches are thin IRL. A pine is normally majestuous (the current one in MTG is thanks to its largeness) and not that stepped with several "tray of leaves" (the real shape is rather conical).

- **[Jungle Tree]** The canopy of the jungle is inherently very dense and luxuriant (like a vegetal roof). The top of your tree is so narrow that the jungle is often crossed by large holes. The vegetation on top should be expanded like that : 
![jungle_trees](https://cloud.githubusercontent.com/assets/7883281/8761791/a6ae6a14-2d63-11e5-8e81-b214f110b623.png)

- **[Acacia Tree]** A slightly thicker layer of leaves might be something worth to consider (the current is dead flat). Example : 
![acacia_trees](https://cloud.githubusercontent.com/assets/7883281/8761866/8a6603c2-2d67-11e5-8533-5c8bb29e87ef.png)

- **[Papyrus]** Putting them at Y=0 is a nice idea (should be keep spawned at Y=1 for completion), but this cause an inadequation with the water : 
![screenshot_20150718_145842](https://cloud.githubusercontent.com/assets/7883281/8761823/494ceea6-2d66-11e5-9b05-618cc20c7ee3.png)
The `Sea` mod has a way to merge the decorations with the water altogether (see screenshots and code) : https://forum.minetest.net/viewtopic.php?id=4627

- **[Miscellaneous]** The sandstone tends to take too much place on the world, mining is highly associated with the grey stone, and Minetest / Minecraft inspired game(s) are primarily, historically mining games. Also : the red desert stone is sadly rarely appearing, unlike on mgv6.

Keep up the work ! :)

**Comment by paramat** [comment]
All good points. The current trees are not perfected yet, i intend to add them soon and then perfect them afterward during 0.4.13.

Pine trees:
I'll consider no branches, however your screenshot is ugly due to simple leaves, it makes all trees look empty. Appletrees and jungletrees will have the same problem.

Jungletrees:
Yes i'll make the jungles a little more dense and dark but by increasing tree number.
I considered a 7-wide tree, but because trees are limited to a height of 16, that makes them look too short. I also like the way the wide roots create a root-maze, a higher density of narrow trees means closer roots for an overgrown feeling.

Acacia trees:
This is something i am considering and will probably try. This is 'acacia tortilis' 'umbrella thorn' which has a wide and very flat canopy, and lots of long pale thorns amonst small leaves.

Papyrus:
I have moved these around so many times now, i like them being in the water, but yes would be better having a special watery papyrus node as a base, ii'll see what i can do. I might move them back to y=1 and surround them with water nodes for a marshy feel.

Stone type:
Sandstone is only 1 biome out of 10 and looks great, the special stone types extend down to -192 so there is stone below.
Desert stone is everywhere desert is, i may need to make deserts a little larger, still tuning the biome points.

**Comment by kilbith** [comment]
Thanks for your answer.

I add some brief notes : 
- Pine tree : simple or fancy leaves does not make a big difference for seeing those ugly "clear dots" in the forrest. And even then, the users who like simple leaves should not be so penalized, aesthetically.
- Papyrus : you could put them on sand at Y=1, surrounded by a blend/noise of water with the sand (like the current biome blending).

**Comment by kilbith** [comment]
Something like that (if you can) : 
![2015-07-20_12 30 22](https://cloud.githubusercontent.com/assets/7883281/8774534/a06afd66-2edf-11e5-8e86-2a8124bb4c49.png)

**Comment by paramat** [comment]
Yes i managed to do that before, it is preferable.

I'm considering keeping the tree braches but rotating them to be all upright, as on the acacia tree, this will make them appear darker when seen from the side.

**Comment by kilbith** [comment]
> the tree braches but rotating them to be all upright

Yes, that's sound better. Also perhaps you should decrease the 3 layers of branches to 2 on the pine tree and give it a more "conical" form.

**Comment by paramat** [comment]
Testing with fancy leaves, i agree the bright branch ends are overkill on the pines, i might even remove the branches. For all trees i'm considering the branches being placed diagonally (and upright) as on the acacia tree. Much testing and tuning to be done.

**Comment by paramat** [comment]
All described in last comment done, also improved jungletree lower branches.

**Comment by kilbith** [comment]
Much better for all trees, that's excellent :+1: Thanks paramat.

**Comment by paramat** [comment]
Yeah i'm moving them now.

**Comment by kilbith** [comment]
I saw the new papyrus dispersion along the coasts, that's perfect.

Congrats and thank you for all that hard work. Everything got satisfaction.

**Comment by paramat** [comment]
Thanks for the useful input.

**Comment by kilbith** [comment]
Hmm, I have a small remark right now : on sand coasts, can you put a sand node under the papyrus (instead of dirt) so that it matches better with the beach environment ?

**Comment by paramat** [comment]
I'm tempted. The papyrus growing ABM checks for dirt or grass below so the mapgen papyrus won't grow (not a problem for me as this would preserve the height differences) so the other MTGame devs will probably insist on dirt or grass below (and have done so before). Actually i think i prefer 2 dirt nodes, not a grass node on top, to simulate a muddy swampy base for the papyrus, will make that change at least.

**Comment by kilbith** [comment]
Yes, a simple dirt is actually better.

**Comment by paramat** [comment]
@kilbith 
Problem is because papyrus propagates light the dirt changes to grass, i think i prefer sand as you suggested, even though in real life papyrus requires soil or sandy soil, well perhaps we can consider sand to be sandy soil. The papyrus-growing ABM could then check for sand to allow growth in sand, to avoid confusing players by having mapgen place papyrus where it will not grow.

**Comment by kilbith** [comment]
+1. Also what I'd like to see is some kind of sand noise around the papyrus and not just underneath. This noise could be a schematic, generated nearby the papyrus with rotation flags.

**Comment by paramat** [comment]
Yeah good idea.

**Comment by kilbith** [comment]
@paramat This is possible to enhance some jungle trees with vines against their leaves ? Obviously the vines would be part of the schematic.

An example : 
![screenshot_20150922_193244](https://cloud.githubusercontent.com/assets/7883281/10026276/17934408-6161-11e5-8d82-ba66c6f272d3.png)

The texture used (pattern by Gambit) : ![xdecor_ivy](https://cloud.githubusercontent.com/assets/7883281/10026302/47cf35c8-6161-11e5-99c8-5cc95fd28c86.png)

**Comment by paramat** [comment]
I'll consider it, i guess it's down to whether the other MTGame devs will accept vine nodes into the game.

**Comment by kilbith** [comment]
Weren't you supposed to put sand below the papyrus ?

![screenshot_20151004_112944](https://cloud.githubusercontent.com/assets/7883281/10267205/54e6ac86-6a8b-11e5-8cf1-3ae1a878b215.png)

**Comment by paramat** [comment]
Yeah there was a sand base, but i then added papyrus to savanna dirt swamps and the sand looked out of place. I guess i will use 2 different papyrus schematics, one sand, one dirt, i'm not keen on the dirt with grass base, dirt would be better but that then grows grass.
I'm tempted to just have papyrus penetrate the water to solve this but people will complain.
I'd rather not add extra sand/dirt noise

**Comment by kilbith** [comment]
> i will use 2 different papyrus schematics, one sand, one dirt, i'm not keen on the dirt with grass base, dirt would be better but that then grows grass.

Agree with that.

As for papyrus, they're normally compacted along and onto the coasts (check on Goole Images).
